#!/usr/bin/env bash
#Script that displays the content of the file /etc/passwd
IFS=$'\n'  
user=( $(awk -F':' '{print $4}' /etc/passwd | tr '\n' ' ') )  
homeDir=( $(awk -F':' '{print $6}' /etc/passwd |tr '\n' ' '))  
unset IFS
